version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # build image
      - run: |
          docker info
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker build -t aspnetweb -f IsUakr.Mvc/Dockerfile.web .
          docker tag aspnetweb registry.heroku.com/$HEROKU_APP_NAME/
          docker push registry.heroku.com/$HEROKU_APP_NAME/aspnetweb               
      # deploy the image
      - run: |
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker build -t aspnethighload -f IsUakr.HighLoad.Ui/Dockerfile.highload .
          docker tag aspnethighload registry.heroku.com/$HEROKU_APP_NAME/highload
          docker push registry.heroku.com/$HEROKU_APP_NAME/aspnethighload
