version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: |
          docker info
          docker build -t highload -f IsUakr.HighLoad.Ui/Dockerfile.Highload .
          docker build -t web -f IsUakr.Mvc/Dockerfile.web .
          docker tag web registry.heroku.com/$HEROKU_APP_NAME/web
          docker tag highload registry.heroku.com/$HEROKU_APP_NAME/highload

      - run: |       
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker push registry.heroku.com/$HEROKU_APP_NAME/web  
          docker push registry.heroku.com/$HEROKU_APP_NAME/highload
          heroku container:release web highload -a $HEROKU_APP_NAME 
